/*
Authors: Daniel Bahrami, Scott Charles
Instructor: Paul Pospisil

Purpose: Contains constants used throughout the game.
*/
#ifndef CONSTANTS_H
#define CONSTANTS_H
#include "types.h"

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 400

#define SOLID         0xFFFF
#define BITS_IN_BYTE  16
#define TWO_CUBED	  4

#define platformHeight 1

#define RIGHTKEY 39
#define LEFTKEY 37

#define gapLength 48
#define gap1_start 80
#define gap2_start 160
#define gap3_start 240
#define gap4_start 320
#define gap5_start 400
#define gap6_start 480

#define lowerPf 1
#define upperPf 6
#define defaultYcordPf 1
#define defaultXcordPf 0
#define defaultDeltaYPf 2 
#define whiteSpacePf 66

#define startOfBorder 15
#define endOfBorder 639


#endif
